### ISSUE TITLE
Set backend pointer over environment variable (or similar)

### ISSUE THREAD

**Issue by empicano** [fastsurvey/console#113]
It would be great if I could set to which backend (local, dev, ...) the console/frontend should point e.g. by an environment variable. Like this I can check more easily whether some backend changes break the frontend.

**Comment by dostuffthatmatters** [comment]
@empicano 

You can now use `f171aa4` to test your backend (not with the new flexible surveys yet). If there is an env var `VITE_API_URL` then this will be used, if not, one of `api.dev.fas...` or `api.fas...` will be used.

If you have a `.env` file present in your directory, it will be loaded automatically.
