### ISSUE TITLE
Duplicating a survey doesn't work for 0.3 console

### ISSUE THREAD

**Issue by empicano** [fastsurvey/console#121]

**Comment by dostuffthatmatters** [comment]
Will be fixed with 0.4 :)

**Comment by empicano** [comment]
Still doesn't work in 0.4, see here:

<img width="600" alt="Screenshot 2021-10-04 at 11 21 32" src="https://user-images.githubusercontent.com/26978146/135826311-4c3e3d21-1e09-47ef-81e4-da1353a74ecd.png">

**Comment by dostuffthatmatters** [comment]
Will fix that in the afternoon!
