### ISSUE TITLE
Tab navigation not aware of field currently selected with the cursor

### ISSUE THREAD

**Issue by empicano** [fastsurvey/console#53]
Commit: 6c6c1dbcd4aae5f46b7ea00d7da517df6ec235ce

When I first use TAB, then the cursor and then again TAB to navigate fields, on the second TAB it jumps to the field than comes after the first TAB (I hope that's understandable 😅 ). I expected it to jump to the field that comes after the one selected via cursor.

https://user-images.githubusercontent.com/26978146/121076738-0888a100-c7d7-11eb-83c3-838ee8bf595f.mov

**Comment by dostuffthatmatters** [comment]
Hm, that's an interesting one :D Will push that to a later sprint - but collecting my thoughts here.

I haven't quite figured out how to programmatically set the current tabIndex. By default every element will get a tabIndex 0 and the tabOrder will be like the order of appearance in the HTML. One can give elements a tabIndex other than 0 to prioritize/deprioritize elements. But assigning every element a specific tabIndex and updating that with input.onFocus is rather sketchy (even more when adding fields inbetween).

Until I found a more elegant way on how to implement this I will leave it like that. Hope that makes sense.
