### ISSUE TITLE
New users confronted with error message on registering without input

### ISSUE THREAD

**Issue by empicano** [fastsurvey/console#61]
Commit: e5176530ea2fbb6cdf9410ea422f79050f43fdaf

When a new user wants to register an account, they are confronted with an error message about the email field, without having touched anything yet. I think that could be discouraging for some people. Maybe we could validate the values when the user clicks on **Login** (which I guess is a typo and should spell "register"?) ?

<img width="412" alt="screenshot" src="https://user-images.githubusercontent.com/26978146/121821845-ed68d600-cc9b-11eb-9931-54eecedb1d0d.png">

**Comment by dostuffthatmatters** [comment]
Yes, that is a typo :D

Will try to hide that error message as good as I can.

**Comment by dostuffthatmatters** [comment]
Idea (just for me): The email field gets focused automatically on page load. Show the validation message once this field is blurred.

**Comment by dostuffthatmatters** [comment]
I decided not to do this for now.

With the desaturated validation message it is less prominent already. Additionally I don't like website where this kind of logic is really intransparent. We can ask a UX expert once we have one :D
