### ISSUE TITLE
Make it possible to see password in clear text in registration/login form

### ISSUE THREAD

**Issue by empicano** [fastsurvey/console#62]
Commit: e5176530ea2fbb6cdf9410ea422f79050f43fdaf

For the registration currently we validate that the user has correctly entered their password by letting them type it in twice. We could skip this step of typing it in a second time if we let them toggle password visibility on/off. I *think* that I have read that somewhere in the NIST guidelines even, but couldn't find it again right now. 

Same goes for the login, could be helpful there, as well.

<img width="412" alt="screenshot" src="https://user-images.githubusercontent.com/26978146/121822395-379f8680-cc9f-11eb-9ec7-d57a266d67b9.png">

**Comment by dostuffthatmatters** [comment]
Yes, definitely helpful!
