### ISSUE TITLE
Start a new draft survey without any fields

### ISSUE THREAD

**Issue by empicano** [fastsurvey/console#66]
Another point that added to the confusion in #65 was that there is already a field (an option field) present, even though the survey is new.

I guess that you add the field because the configuration is only valid with at least one field. I think you already brought it up once with me that that could be confusing. Maybe we should relax these rules for drafts (in some future version?), I don't have a good idea though how this could be communicated clearly through the UI, though, that they are validated differently.

Also, probably the best would be to keep the differences in validation between drafts and published surveys as few as possible.

**Comment by dostuffthatmatters** [comment]
In the future definitely!

Right now: Validation for draft and published the same and a new survey should have a valid config.
